Lift requires outside of modules
To work around:
Error: Linker error in the native compiler. Are you using Require inside
a nested Module declaration?
This use case is not supported, but disabling the native compiler may
help.